services:

  sqlserver-test:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-test
    ports:
      - "11433:1433"
    environment:
      TZ: Europe/Berlin
      SA_PASSWORD: "WellAPasswordICanUseInStackOverflow!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SLEEP: 7
    stdin_open: true
    volumes:
      - test_db-data:/var/opt/mssql
volumes:
  test_db-data:
